export interface ParentGuardian {
  id: string;
  student_id?: string;
  parent_id?: string;
  relation: string;
  name?: string;
  first_name?: string;
  last_name?: string;
  phone?: string;
  email?: string;
  occupation?: string;
  is_primary: boolean;
  qualification?: string;
  aadhar_no?: string;
  dob?: string;
  address?: string;
  guardian_relation?: string;
  alternate_mobile?: string;
  alternate_email?: string;
  emergency_mobile?: string;
}

export interface Student {
  id: string;
  school_id: string;
  academic_year_id?: string;
  admission_no: string;
  first_name: string;
  last_name: string;
  gender: string;
  dob?: string;
  email?: string;
  sms_mobile?: string;
  whatsapp_mobile?: string;
  blood_group?: string;
  aadhar_no?: string;
  saral_id?: string;
  reg_no?: string;
  roll_number?: string;
  card_number?: string;
  cbse_reg_no?: string;
  ledger_no?: string;
  pen?: string;
  apaar_id?: string;
  caste_category?: string;
  student_category?: string;
  house_category?: string;
  fee_type?: string;
  class_section_id?: string;
  class_name?: string;
  section?: string;
  papers?: string[];
  additional_papers?: string[];
  contact_address?: string;
  pin_code?: string;
  permanent_address?: string;
  country?: string;
  city_state?: string;
  registration_date?: string;
  joining_date?: string;
  relieving_date?: string;
  class_promoted_date?: string;
  last_school_name?: string;
  last_school_class?: string;
  last_school_subjects?: string;
  last_school_attendance?: number;
  transfer_certificate_no?: string;
  fee_concession?: string;
  photo_url?: string;
  student_type?: string;
  hosteller: boolean;
  admission_type?: string;
  status: string;
  tc_generated: boolean;
  registration_id?: string;
  has_sibling: boolean;
  sibling_student_id?: string;
  created_at: string;
  parent_guardians?: ParentGuardian[];
}

export interface ClassSection {
  id: string;
  school_id: string;
  academic_year_id: string;
  class_name: string;
  section: string;
  class_teacher_id?: string;
}
